name: start-laravel

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Docker Version
        run: docker version

      - name: Build Docker Images
        run: docker-compose build

      - name: Start Docker Containers
        run: docker-compose up -d

      - name: OS Version
        run: |
          docker-compose exec -T backend cat /etc/os-release
          docker-compose exec -T backend cat /etc/debian_version

      - name: PHP Version
        run: docker-compose exec -T backend php --version

      - name: Composer Version
        run: docker-compose exec -T backend composer --version

      - name: Laravel Version
        run: docker-compose exec -T backend php artisan --version

      - name: Laravel Migrate Testing
        run: docker-compose exec -T backend php artisan migrate

      - name: Laravel Rollback Testing
        run: docker-compose exec -T backend php artisan migrate:refresh

      - name: Laravel Seeding Testing
        run: docker-compose exec -T backend php artisan db:seed

      - name: Laravel PHPUnit Testing
        run: docker-compose exec -T backend php artisan test
